import type { Metadata } from "next";
import styles from "./items.module.scss";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <div className={styles["ui-container"]}>
     {children}
   </div>
  );
}
